import image1 from "../../assets/chat1.png";
import image2 from "../../assets/chat2.png";
import image3 from "../../assets/chat3.png";
import image4 from "../../assets/chat4.png";

export const chats = [
  {
    name: "Folake",
    icon: image1,
    text: "Hello everybody! I’m Folake.",
    time: "08.43",
  },
  {
    name: "Bradon",
    icon: image2,
    text: "Will do, super, thank you",
    time: "Tue",
  },
  {
    name: "Solape",
    icon: image3,
    text: "Uploaded a picture.",
    time: "Sun",
  },
  {
    name: "Marcel",
    icon: image4,
    text: "Here is another post, if you...",
    time: "23 Sep",
  },
  {
    name: "Folake",
    icon: image1,
    text: "Hello everybody! I’m Folake.",
    time: "08.43",
  },
  {
    name: "Bradon",
    icon: image2,
    text: "Will do, super, thank you",
    time: "Tue",
  },
  {
    name: "Solape",
    icon: image3,
    text: "Uploaded a picture.",
    time: "Sun",
  },
  {
    name: "Marcel",
    icon: image4,
    text: "Here is another post, if you...",
    time: "23 Sep",
  },
  {
    name: "Folake",
    icon: image1,
    text: "Hello everybody! I’m Folake.",
    time: "08.43",
  },
  {
    name: "Bradon",
    icon: image2,
    text: "Will do, super, thank you",
    time: "Tue",
  },
  {
    name: "Solape",
    icon: image3,
    text: "Uploaded a picture.",
    time: "Sun",
  },
  {
    name: "Marcel",
    icon: image4,
    text: "Here is another post, if you...",
    time: "23 Sep",
  },
  {
    name: "Folake",
    icon: image1,
    text: "Hello everybody! I’m Folake.",
    time: "08.43",
  },
  {
    name: "Bradon",
    icon: image2,
    text: "Will do, super, thank you",
    time: "Tue",
  },
  {
    name: "Solape",
    icon: image3,
    text: "Uploaded a picture.",
    time: "Sun",
  },
  {
    name: "Marcel",
    icon: image4,
    text: "Here is another post, if you...",
    time: "23 Sep",
  },
  {
    name: "Folake",
    icon: image1,
    text: "Hello everybody! I’m Folake.",
    time: "08.43",
  },
  {
    name: "Bradon",
    icon: image2,
    text: "Will do, super, thank you",
    time: "Tue",
  },
  {
    name: "Solape",
    icon: image3,
    text: "Uploaded a picture.",
    time: "Sun",
  },
  {
    name: "Marcel",
    icon: image4,
    text: "Here is another post, if you...",
    time: "23 Sep",
  },
  {
    name: "Folake",
    icon: image1,
    text: "Hello everybody! I’m Folake.",
    time: "08.43",
  },
  {
    name: "Bradon",
    icon: image2,
    text: "Will do, super, thank you",
    time: "Tue",
  },
  {
    name: "Solape",
    icon: image3,
    text: "Uploaded a picture.",
    time: "Sun",
  },
  {
    name: "Marcel",
    icon: image4,
    text: "Here is another post, if you...",
    time: "23 Sep",
  },
  ,
  {
    name: "Folake",
    icon: image1,
    text: "Hello everybody! I’m Folake.",
    time: "08.43",
  },
  {
    name: "Bradon",
    icon: image2,
    text: "Will do, super, thank you",
    time: "Tue",
  },
  {
    name: "Solape",
    icon: image3,
    text: "Uploaded a picture.",
    time: "Sun",
  },
  {
    name: "Marcel",
    icon: image4,
    text: "Here is another post, if you...",
    time: "23 Sep",
  },
  {
    name: "Folake",
    icon: image1,
    text: "Hello everybody! I’m Folake.",
    time: "08.43",
  },
  {
    name: "Bradon",
    icon: image2,
    text: "Will do, super, thank you",
    time: "Tue",
  },
  {
    name: "Solape",
    icon: image3,
    text: "Uploaded a picture.",
    time: "Sun",
  },
  {
    name: "Marcel",
    icon: image4,
    text: "Here is another post, if you...",
    time: "23 Sep",
  },
  {
    name: "Folake",
    icon: image1,
    text: "Hello everybody! I’m Folake.",
    time: "08.43",
  },
  {
    name: "Bradon",
    icon: image2,
    text: "Will do, super, thank you",
    time: "Tue",
  },
  {
    name: "Solape",
    icon: image3,
    text: "Uploaded a picture.",
    time: "Sun",
  },
  {
    name: "Marcel",
    icon: image4,
    text: "Here is another post, if you...",
    time: "23 Sep",
  },
  {
    name: "Folake",
    icon: image1,
    text: "Hello everybody! I’m Folake.",
    time: "08.43",
  },
  {
    name: "Bradon",
    icon: image2,
    text: "Will do, super, thank you",
    time: "Tue",
  },
  {
    name: "Solape",
    icon: image3,
    text: "Uploaded a picture.",
    time: "Sun",
  },
  {
    name: "Marcel",
    icon: image4,
    text: "Here is another post, if you...",
    time: "23 Sep",
  },
  {
    name: "Folake",
    icon: image1,
    text: "Hello everybody! I’m Folake.",
    time: "08.43",
  },
  {
    name: "Bradon",
    icon: image2,
    text: "Will do, super, thank you",
    time: "Tue",
  },
  {
    name: "Solape",
    icon: image3,
    text: "Uploaded a picture.",
    time: "Sun",
  },
  {
    name: "Marcel",
    icon: image4,
    text: "Here is another post, if you...",
    time: "23 Sep",
  },
  {
    name: "Marcel",
    icon: image4,
    text: "Here is another post, if you...",
    time: "23 Sep",
  },
  {
    name: "Folake",
    icon: image1,
    text: "Hello everybody! I’m Folake.",
    time: "08.43",
  },
  {
    name: "Bradon",
    icon: image2,
    text: "Will do, super, thank you",
    time: "Tue",
  },
  {
    name: "Solape",
    icon: image3,
    text: "Uploaded a picture.",
    time: "Sun",
  },
  {
    name: "Marcel",
    icon: image4,
    text: "Here is another post, if you...",
    time: "23 Sep",
  },
  {
    name: "Folake",
    icon: image1,
    text: "Hello everybody! I’m Folake.",
    time: "08.43",
  },
  {
    name: "Bradon",
    icon: image2,
    text: "Will do, super, thank you",
    time: "Tue",
  },
  {
    name: "Solape",
    icon: image3,
    text: "Uploaded a picture.",
    time: "Sun",
  },
  {
    name: "Marcel",
    icon: image4,
    text: "Here is another post, if you...",
    time: "23 Sep",
  },
  {
    name: "Folake",
    icon: image1,
    text: "Hello everybody! I’m Folake.",
    time: "08.43",
  },
  {
    name: "Bradon",
    icon: image2,
    text: "Will do, super, thank you",
    time: "Tue",
  },
  {
    name: "Solape",
    icon: image3,
    text: "Uploaded a picture.",
    time: "Sun",
  },
  {
    name: "Marcel",
    icon: image4,
    text: "Here is another post, if you...",
    time: "23 Sep",
  },
  {
    name: "Folake",
    icon: image1,
    text: "Hello everybody! I’m Folake.",
    time: "08.43",
  },
  {
    name: "Bradon",
    icon: image2,
    text: "Will do, super, thank you",
    time: "Tue",
  },
  {
    name: "Solape",
    icon: image3,
    text: "Uploaded a picture.",
    time: "Sun",
  },
  {
    name: "Marcel",
    icon: image4,
    text: "Here is another post, if you...",
    time: "23 Sep",
  },
  {
    name: "Folake",
    icon: image1,
    text: "Hello everybody! I’m Folake.",
    time: "08.43",
  },
  {
    name: "Bradon",
    icon: image2,
    text: "Will do, super, thank you",
    time: "Tue",
  },
  {
    name: "Solape",
    icon: image3,
    text: "Uploaded a picture.",
    time: "Sun",
  },
  {
    name: "Marcel",
    icon: image4,
    text: "Here is another post, if you...",
    time: "23 Sep",
  },
];
